### ISSUE TITLE
Decode option for other encoding than UTF-8

### ISSUE THREAD

**Issue by cfrancois7** [fredericjs/surfalize#2]
I tried the package but I met an error about the decoding.

I should be nice if we can modify the encoding, such as 'utf-8' to 'latin-1' during `Surface.loads`.
For instance I worked with a file encoded as `latin-1` and two changes were needed : 

`encoding='latin-1'`

In `read_binary_layout`
```
if isinstance(unpacked_data, bytes):
            unpacked_data = unpacked_data.decode(encoding).strip()
```

And a strip apply with '\x00' in `get_unit_conversion` that sometimes breaks the code for kind unit.

```
Returns
    -------
    factor: float
        Factor by which to multiply the original values.
    """
    from_unit = from_unit.strip('\x00')   <------- HERE
    if from_unit not in UNIT_EXPONENT or to_unit not in UNIT_EXPONENT:
```

**Comment by fredericjs** [comment]
Can you provide an example file where this error occurs? I'll look into it.

**Comment by cfrancois7** [comment]
The error raise when I call the `load` method of the `Surface` class.

Example: 
```
from surfalize import Surface
data_path = Path('./data/my_digital_surf_file.sur')
surface_d = Surface.load(data_path )
```

The raised error: 
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[3], line 1
----> 1 surface_d = Surface.load(path_measures_d)
      2 surface_i = Surface.load(path_measures_i, encoding='latin-1')

File ~/.anaconda3/envs/metrology/lib/python3.11/site-packages/surfalize/surface.py:268, in Surface.load(cls, filepath, encoding)
    255 @classmethod
    256 def load(cls, filepath, encoding='utf-8'):
    257     """
    258     Classmethod to load a topography from a file.
    259 
   (...)
    266     surface: surfalize.Surface
    267     """
--> 268     return cls(*load_file(filepath, encoding=encoding))

File ~/.anaconda3/envs/metrology/lib/python3.11/site-packages/surfalize/file/loader.py:29, in load_file(filepath, encoding)
     25 except KeyError:
     26     raise UnsupportedFileFormatError(
     27         f"File format {filepath.suffix} is currently not supported."
     28     )
---> 29 return loader(filepath)

File ~/.anaconda3/envs/metrology/lib/python3.11/site-packages/surfalize/file/sur.py:75, in read_sur(filepath, encoding)
     73 filesize = filepath.stat().st_size
     74 with open(filepath, "rb") as filehandle:
---> 75     header = read_binary_layout(filehandle, LAYOUT_HEADER, encoding=encoding)
     77     if header["code"] != MAGIC or header["version_number"] != 1:
     78         raise CorruptedFileError

File ~/.anaconda3/envs/metrology/lib/python3.11/site-packages/surfalize/file/common.py:93, in read_binary_layout(filehandle, layout, fast, encoding)
     91     unpacked_data = struct.unpack(f"{format}", filehandle.read(size))[0]
     92     if isinstance(unpacked_data, bytes):
---> 93         unpacked_data = unpacked_data.decode(encoding).strip()
     94     result[name] = unpacked_data
     95 return result

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte
```

I fixed for myself the code locally. Now I can propose a decoding option : `surface_i = Surface.load(path, encoding='latin-1')`.
I can create a PR to talk about the problem and the proposition.
What is the commit id of the fix about the `\x00` to rebase my local code before doing the PR?

**Comment by fredericjs** [comment]
Sorry for the late reply and thanks for providing an examplary fix. I have implemented it on the develop branch and it will be part of the next release. In the meantime, feel free to directly install from the develop branach.

**Comment by cfrancois7** [comment]
I would like to reopen the issue.

I'm running on the surfalize==0.14.2, WSL 2 - ubuntu based.

I have issue with the encoding.
By adding a print around the unpacking application, I saw the encoding option has no effect.

`surfalize/file/common.py`
```python
size = struct.calcsize(format)
unpacked_data = struct.unpack(f"{format}", filehandle.read(size))[0]
if isinstance(unpacked_data, bytes):
    unpacked_data = unpacked_data.decode(encoding).rstrip(" \x00")
    print("encoding in after unpacked_data", encoding)
data[self.name] = unpacked_data
```

It generates : 
`surface_d = Surface.load(sur_path, format=".sur", encoding='latin-1')`
```python
ENCODING in READ_SUR: latin-1
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
ENCODING in READ_SUR: latin-1
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
encoding in after unpacked_data utf-8
....
```

And raises the error 
```python
File lib/python3.11/site-packages/surfalize/file/common.py:401, in FileHandler.read(self, read_image_layers, encoding)
    [395](.../lib/python3.11/site-packages/surfalize/file/common.py:395)                 warnings.warn(
    [396](.../lib/python3.11/site-packages/surfalize/file/common.py:396)                     f"The file suffix indicates a file of type {self.file.suffix}. However, the file "
    [397](.../lib/python3.11/site-packages/surfalize/file/common.py:397)                     f"seems to actually be of type {reader._suffix}. Check if the file extensions is "
...
--> [186](.../lib/python3.11/site-packages/surfalize/file/common.py:186)     unpacked_data = unpacked_data.decode(encoding).rstrip(" \x00")
    [187](.../lib/python3.11/site-packages/surfalize/file/common.py:187)     print("encoding in after unpacked_data", encoding)
    [188](.../lib/python3.11/site-packages/surfalize/file/common.py:188) data[self.name] = unpacked_data

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 0: invalid start byte
```

**Comment by fredericjs** [comment]
Ah I sde, the encoding argument probably got lost during a rewrite of the file reading functions. I will fix make a quick fix. Can you please provide one of your latin-1 encoded files to be added to the set of test files so this doesn't happen in the future?

**Comment by cfrancois7** [comment]
I would like to avoid to diffuse the image too largely.
How can I send you the file ?
Have you a service or one email ?

**Comment by fredericjs** [comment]
If you don't want the file to be public then no need to send it. I was thinking to add it to the unittests, so it would be public.

**Comment by fredericjs** [comment]
This issue should be fixed with v0.14.3. I also added an `'auto'` option for the encoding parameter to automatically infer the encoding.

**Comment by taki-climb** [comment]
Hi, @fredericjs 

# Can't read vk4 file which is encoded without "utf-8"

I'm still encountering similar issue like above.

---

## **Prerequisite**

residential area : Japan
device ; keyence vk-x100 series (outputfile's extension .vk4)
guessed extension : unicode_escape ( mention below )

## **Issue**

after installing surfalize == 0.14.3. and then loaded test.vk4 file that I measured.
below error was displayed.
Surface.load("test.vk4",encoding="unicode_escape")
`

---

UnicodeDecodeError Traceback (most recent call last)
Cell In[39], line 1
----> 1 Surface.load("test.vk4",encoding="unicode_escape")

File /usr/local/lib/python3.9/dist-packages/surfalize/surface.py:299, in Surface.load(cls, path_or_buffer, format, encoding, read_image_layers)
 275 @classmethod
 276 def load(cls, path_or_buffer, format=None, encoding='utf-8', read_image_layers=False):
 277 """
 278 Classmethod to load a topography from a file.
 279 
(...)
 297 surface : surfalize.Surface
 298 """
--> 299 raw_surface = FileHandler(path_or_buffer, format_=format).read(encoding=encoding,
 300 read_image_layers=read_image_layers)
 301 return cls.from_raw_surface(raw_surface)

File /usr/local/lib/python3.9/dist-packages/surfalize/file/common.py:379, in FileHandler.read(self, read_image_layers, encoding)
 375 warnings.warn(f'The file suffix indicates a file of type {self.file.suffix}. However, the file '
 376 f'seems to actually be of type {reader._suffix}. Check if the file extensions is '
 377 f'correct. The file was now loaded as {reader._suffix}.')
 378 filehandle.seek(0, 0)
--> 379 return reader(filehandle, read_image_layers=read_image_layers, encoding=encoding)
 380 if exception is not None:
 381 raise exception

File /usr/local/lib/python3.9/dist-packages/surfalize/file/vk.py:176, in read_vk4(filehandle, read_image_layers, encoding)
 174 image_layers = None
 175 height_layer = read_height_layer(filehandle, offset_table['height'])
--> 176 metadata.update(read_string_data(filehandle, offset_table['string_data']))
 178 scale_factor = get_unit_conversion(FIXED_UNIT, 'um')
 179 scale_factor_height = scale_factor * measurement_conditions['z_length_per_digit']

File /usr/local/lib/python3.9/dist-packages/surfalize/file/vk.py:152, in read_string_data(filehandle, offset)
 149 size_title = struct.unpack('I', filehandle.read(4))[0] * 2
 150 # Every character is followed by a null byte. Therefore, we read twice the since of the expected string length and slice to
 151 # remove every second character
--> 152 str_data['title'] = filehandle.read(size_title).decode()[::2]
 153 size_lens_name = struct.unpack('I', filehandle.read(4))[0] * 2
 154 # Same here

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte
`

## **Estimated Solution**

after I noticed this error. I assumed that this error caused by lack of arguments related to encoding option in /surfalize/files/vk file.

## Provisional Treatment

I reinstalled surfalize==0.14.1 (I don't have specific reason that installed this version).

and rewrite /surfalize/files/vk like below. (It'll be displayed diff comparison between vk4 file about 0.14.3 version and 0.14.1 version after I rewrited (only added encoding option)).

Currently the problem seems to be disappeared.

![Image](https://github.com/user-attachments/assets/941a9f26-93e9-48d4-a20a-bd4872de377e)

## Request

Please check some encoding option of some files like vk4 file again for future issue.

for verification test actual vk4 file that I encountered above error send below.

[[example.zip](https://github.com/user-attachments/files/18729591/example.zip)](https://github.com/user-attachments/files/18729591/example.zip)
